// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: internal/grpc/proto/stats.proto

package stats

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserStatsService_GetUserStats_FullMethodName = "/stats.UserStatsService/GetUserStats"
)

// UserStatsServiceClient is the client statistics for UserStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserStatsServiceClient interface {
	GetUserStats(ctx context.Context, in *UserStatsRequest, opts ...grpc.CallOption) (*UserStatsResponse, error)
}

type userStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserStatsServiceClient(cc grpc.ClientConnInterface) UserStatsServiceClient {
	return &userStatsServiceClient{cc}
}

func (c *userStatsServiceClient) GetUserStats(ctx context.Context, in *UserStatsRequest, opts ...grpc.CallOption) (*UserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserStatsResponse)
	err := c.cc.Invoke(ctx, UserStatsService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserStatsServiceServer is the server statistics for UserStatsService service.
// All implementations must embed UnimplementedUserStatsServiceServer
// for forward compatibility.
type UserStatsServiceServer interface {
	GetUserStats(context.Context, *UserStatsRequest) (*UserStatsResponse, error)
	mustEmbedUnimplementedUserStatsServiceServer()
}

// UnimplementedUserStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserStatsServiceServer struct{}

func (UnimplementedUserStatsServiceServer) GetUserStats(context.Context, *UserStatsRequest) (*UserStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedUserStatsServiceServer) mustEmbedUnimplementedUserStatsServiceServer() {}
func (UnimplementedUserStatsServiceServer) testEmbeddedByValue()                          {}

// UnsafeUserStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserStatsServiceServer will
// result in compilation errors.
type UnsafeUserStatsServiceServer interface {
	mustEmbedUnimplementedUserStatsServiceServer()
}

func RegisterUserStatsServiceServer(s grpc.ServiceRegistrar, srv UserStatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserStatsService_ServiceDesc, srv)
}

func _UserStatsService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserStatsServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserStatsService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserStatsServiceServer).GetUserStats(ctx, req.(*UserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserStatsService_ServiceDesc is the grpc.ServiceDesc for UserStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.UserStatsService",
	HandlerType: (*UserStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserStats",
			Handler:    _UserStatsService_GetUserStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/stats.proto",
}
