// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/grpc/proto/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsRequest) Reset() {
	*x = UserStatsRequest{}
	mi := &file_internal_grpc_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsRequest) ProtoMessage() {}

func (x *UserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsRequest.ProtoReflect.Descriptor instead.
func (*UserStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *UserStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type UserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsrCreated    int64                  `protobuf:"varint,1,opt,name=usr_created,json=usrCreated,proto3" json:"usr_created,omitempty"`
	UsrUpdated    int64                  `protobuf:"varint,2,opt,name=usr_updated,json=usrUpdated,proto3" json:"usr_updated,omitempty"`
	UsrDeleted    int64                  `protobuf:"varint,3,opt,name=usr_deleted,json=usrDeleted,proto3" json:"usr_deleted,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_internal_grpc_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatsResponse) GetUsrCreated() int64 {
	if x != nil {
		return x.UsrCreated
	}
	return 0
}

func (x *UserStatsResponse) GetUsrUpdated() int64 {
	if x != nil {
		return x.UsrUpdated
	}
	return 0
}

func (x *UserStatsResponse) GetUsrDeleted() int64 {
	if x != nil {
		return x.UsrDeleted
	}
	return 0
}

func (x *UserStatsResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

var File_internal_grpc_proto_stats_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/grpc/proto/stats.proto\x12\x05stats\"*\n" +
	"\x10UserStatsRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"\x8e\x01\n" +
	"\x11UserStatsResponse\x12\x1f\n" +
	"\vusr_created\x18\x01 \x01(\x03R\n" +
	"usrCreated\x12\x1f\n" +
	"\vusr_updated\x18\x02 \x01(\x03R\n" +
	"usrUpdated\x12\x1f\n" +
	"\vusr_deleted\x18\x03 \x01(\x03R\n" +
	"usrDeleted\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period2U\n" +
	"\x10UserStatsService\x12A\n" +
	"\fGetUserStats\x12\x17.stats.UserStatsRequest\x1a\x18.stats.UserStatsResponseB\vZ\tgen/statsb\x06proto3"

var (
	file_internal_grpc_proto_stats_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_stats_proto_rawDescData []byte
)

func file_internal_grpc_proto_stats_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_stats_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_stats_proto_rawDesc), len(file_internal_grpc_proto_stats_proto_rawDesc)))
	})
	return file_internal_grpc_proto_stats_proto_rawDescData
}

var file_internal_grpc_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_proto_stats_proto_goTypes = []any{
	(*UserStatsRequest)(nil),  // 0: stats.UserStatsRequest
	(*UserStatsResponse)(nil), // 1: stats.UserStatsResponse
}
var file_internal_grpc_proto_stats_proto_depIdxs = []int32{
	0, // 0: stats.UserStatsService.GetUserStats:input_type -> stats.UserStatsRequest
	1, // 1: stats.UserStatsService.GetUserStats:output_type -> stats.UserStatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_stats_proto_init() }
func file_internal_grpc_proto_stats_proto_init() {
	if File_internal_grpc_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_stats_proto_rawDesc), len(file_internal_grpc_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_stats_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_stats_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_stats_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_stats_proto = out.File
	file_internal_grpc_proto_stats_proto_goTypes = nil
	file_internal_grpc_proto_stats_proto_depIdxs = nil
}
